### ISSUE TITLE
ACM Website Redesign Proposal

### ISSUE THREAD

**Issue by bjessing** [ColoradoSchoolOfMines/mozzarella#15]
Hello!

Please follow the URL below to view the complete redesign proposal, including:
- New page tabs
- Redesigned page layout
- ACM project listing space

Update: Link now shareable (oops!)

https://docs.google.com/a/mymail.mines.edu/document/d/1qUKWrfjFSjszSa0LL-r8pwizSq70XV8MFQ-z4FSazaE/edit?usp=sharing

I myself do not know yet how to code websites, but if someone reads the proposal & wants to work on this together, I'm totally for it! I could use the learning experience, and hopefully these designs could aid in ACM's pursuits.

Thanks, and enjoy!

~ Benjamin Jessing, ACM & LUG Member

**Comment by jackrosenthal** [comment]
Hi Ben,

I'm not able to open the Google Doc (permission issue?). Maybe you could make it a public viewable, or just copy/paste here?

Jack

**Comment by sumnerevans** [comment]
@bjessing, echoing what @jackrosenthal said, in the saring options on Google Drive, you can click the "get sharing link" button to make it available for anyone with the link. Since this is an Open Source project, it would be good to make all documentation available to want-to-be contributors.

**Comment by bjessing** [comment]
Oops! Sorry about that, here is the new link:

https://docs.google.com/a/mymail.mines.edu/document/d/1qUKWrfjFSjszSa0LL-r8pwizSq70XV8MFQ-z4FSazaE/edit?usp=sharing

Thank you for letting me know, I had no idea about the Shareable Link option! Please let me know if it still doesn't work.

**Comment by jackrosenthal** [comment]
It seems that all of the design considerations in this document have either been resolved directly or indirectly (by another feature), so I'm going to close this.
