### ISSUE TITLE
Add social links to the footer

### ISSUE THREAD

**Issue by sumnerevans** [ColoradoSchoolOfMines/mozzarella#16]
Add link to the ColoradoSchoolOfMines org as well as (optionally) social media sites (Facebook, etc.).

A few design thoughts:
- Maybe these links should be a configurable option from the admin page?
- These links should be just the logo as Fontawesome fonts.

**Comment by jackrosenthal** [comment]
Don't forget that the paste configuration can be used for global config options... you don't have to create data models just for config.
