### ISSUE TITLE
Make Projects searchable

### ISSUE THREAD

**Issue by sumnerevans** [ColoradoSchoolOfMines/mozzarella#38]
## User Story

Create a search box in the header. Eventually this will become the global search functionality. When the user presses the search button, they will be shown the search results page where they can navigate to projects.

## Design Considerations
- Make sure this is extensible. We need to be able to let people search the wiki and possibly other things.
- Since this is an addition to the navigation bar, we need to be very careful about the visual design because it will be visible from every page. Bootstrap has some nice components for this, but we need to make sure they work well on mobile and a variety of screen sizes.

**Comment by sumnerevans** [comment]
Work is being done on `project-searchable` branch.

**Comment by jackrosenthal** [comment]
Do you or anyone else plan on finishing your feature, or should I close this and remove your branch?
