### ISSUE TITLE
Make users searchable

### ISSUE THREAD

**Issue by sumnerevans** [ColoradoSchoolOfMines/mozzarella#43]
## User Story
I want to be able to search for ACM members (users). This should be integrated with the work done on #38.

## Design
- this should search the user's name, username, title, and bio

**Comment by sumnerevans** [comment]
Lots of overlap between this and #38.

**Comment by jackrosenthal** [comment]
I'm going to close this for now, as it just seems to be a feature that Sumner wanted... if you want it, then you can implement it.
