### ISSUE TITLE
Create proposal for Field Session project

### ISSUE THREAD

**Issue by sumnerevans** [ColoradoSchoolOfMines/mozzarella#45]
We want to create a field session project to help improve this website. The main goal of the project will be to make the site flexible enough to be used by other clubs. If they get done with that, we can have them work on converting the LUG website over to this codebase.

## Todo
- [ ] Create a good project description.
    - [ ] Define scope
- [ ] Define a set of tasks to work on. (Alternatively we could make them do this, it's honestly good to learn how to read a codebase and figure out what needs to be changed. We should have at least a couple of tasks ready, however.)

**Comment by jackrosenthal** [comment]
Done... here is the proposal.

[mozzarella-fs-proposal.pdf](https://github.com/ColoradoSchoolOfMines/mozzarella/files/1749603/mozzarella-fs-proposal.pdf)

[mozzarella-fs-proposal.txt](https://github.com/ColoradoSchoolOfMines/mozzarella/files/1749605/mozzarella-fs-proposal.txt)
