### ISSUE TITLE
Create a name for our project

### ISSUE THREAD

**Issue by jackrosenthal** [ColoradoSchoolOfMines/mozzarella#48]
If we want our web application to be something usable by many clubs, we'll want a catchy sounding name for it.

Any suggestions?

**Comment by sumnerevans** [comment]
Do we want this to be a kind of codename or be descriptive?

**Comment by jackrosenthal** [comment]
Something we could use to brand our project. "ACM Website" ain't gonna cut it for selling this to other clubs.

Wether that's descriptive or not is an entirely separate question.

**Comment by jackrosenthal** [comment]
Here's an idea: OrgPy.

It represents that this project is for student organizations, and the python underpinnings.

Thoughts?

**Comment by sumnerevans** [comment]
Those are pretty good, what about TurbOrg? Keeps the "org" factor, and emphasizes that it's built on TurboGears.

**Comment by jackrosenthal** [comment]
Thinking of steering away from the "org" names, reminds me too much of OrgSync (yuck!)

How about "Pepperoni"? Reflects our pizza consumption, and the target audience really well!

**Comment by samsartor** [comment]
Mozzarella
