### ISSUE TITLE
Consider how we deal with tags/skills

### ISSUE THREAD

**Issue by sumnerevans** [ColoradoSchoolOfMines/mozzarella#51]
Potentially, both projects and users will have the concept of "tags". On the user page, allow the user to add "skills" to their profile, these could be linked with "tags" on projects. For example, the Rust tag could be associated with users and projects.

**Comment by jackrosenthal** [comment]
What's wrong with this::

    USER ---- M:N ---- TAG ---- M:N ---- PROJECT

**Comment by sumnerevans** [comment]
@jackrosenthal , nothing in particular. That is what I was advocating for. Everyone else thought this was overkill and that we should just use a comma separated list to store this information.

CC: @samsartor , @edwargix , @jordannewport , @josephmckinsey , @robozman

**Comment by jackrosenthal** [comment]
> Everyone else thought this was overkill and that we should just use a comma separated list to store this information.

I just puked in my mouth a little. Most certainly do not implement it using a comma separated list...

**Comment by sumnerevans** [comment]
@samsartor , @edwargix , @jordannewport , @josephmckinsey , @robozman , Jack's with me on this one. Please implement this as a tag table that has relations to User and Project.

**Comment by samsartor** [comment]
@sumnerevans @jackrosenthal I agree with the m:n approach.

However, I vote that we split it off into it's own issue/branch/PR separate from project/profile pages.

Issues need to remain granular.

**Comment by sumnerevans** [comment]
@samsartor, then let's not add tags at all for now.

**Comment by samsartor** [comment]
@sumnerevans Agreed
