### ISSUE TITLE
Design mechanism for configuration of site-specific assets from file system

### ISSUE THREAD

**Issue by jackrosenthal** [ColoradoSchoolOfMines/mozzarella#77]
Need a way to specify:

- Directory that corresponds to site-specific assets from the file system
- What file in that directory is for a logo
- What file in that directory is site-specific CSS
- Anything else you would think is necessary.

Post what will be put in ``config.ini`` etc. here and I can review.

**Comment by jackrosenthal** [comment]
This also includes documentation of config formats in Sphinx

**Comment by JadElClemens** [comment]
Values defined along with defaults

- Directory that corresponds to site-specific assets from the file system
assets_dir = %(here)s/customassets/

- What file in that directory is for a logo
logo_file = logo.webp

- What file in that directory is site-specific CSS
custom_css = custom.css

**Comment by JadElClemens** [comment]
From what I understand multiple stylesheets are composited into one at load time so the custom stylesheet can be loaded after the default in order to supersede default styles.

Might also use a "website_name" parameter (would equal "acmwebsite" in the current config) if the user needs to reference files (or names of such) within the TG environment - probably useful for plugins

**Comment by jackrosenthal** [comment]
> From what I understand multiple stylesheets are composited into one at load time so the custom stylesheet can be loaded after the default in order to supersede default styles.

The web browser can handle this for you... just link the custom style sheet if one exists.

> Might also use a "website_name" parameter (would equal "acmwebsite" in the current config) if the user needs to reference files (or names of such) within the TG environment - probably useful for plugins

Can you explain what you mean? The package name will change to ``mozzarella`` soon.

**Comment by JadElClemens** [comment]
> Can you explain what you mean? The package name will change to mozzarella soon.
I guess I meant in order to change the site name as far as TurboGears is concerned. I realize that that configuration is done during TG setup, so I guess it's irrelevant.
